apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-rabbitmq
spec:
  selector:
    matchLabels:
      app: onlyoffice-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: onlyoffice-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        ports:
        - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: onlyoffice-rabbitmq
